/*
 * This source file was generated by the Gradle 'init' task
 */
package lista2;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }
    @RestController;
    @RequestMapping("/app")
    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
